function out1 = scaled_sigma_w(in1,in2)
%SCALED_SIGMA_W
%    OUT1 = SCALED_SIGMA_W(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    04-Aug-2024 14:45:27

Q1_1 = in1(1);
Q1_2 = in1(2);
Q1_3 = in1(3);
Q1_4 = in1(4);
Q1_5 = in1(5);
Q1_6 = in1(6);
Q2_2 = in1(8);
Q2_3 = in1(9);
Q2_4 = in1(10);
Q2_5 = in1(11);
Q2_6 = in1(12);
Q3_3 = in1(15);
Q3_4 = in1(16);
Q3_5 = in1(17);
Q3_6 = in1(18);
Q4_4 = in1(22);
Q4_5 = in1(23);
Q4_6 = in1(24);
Q5_5 = in1(29);
Q5_6 = in1(30);
Q6_6 = in1(36);
u1 = in2(1,:);
u2 = in2(2,:);
u3 = in2(3,:);
u4 = in2(4,:);
u5 = in2(5,:);
u6 = in2(6,:);
t2 = Q1_2.*u1.*u2;
t3 = Q1_3.*u1.*u3;
t4 = Q1_4.*u1.*u4;
t5 = Q1_5.*u1.*u5;
t6 = Q1_6.*u1.*u6;
t7 = Q2_3.*u2.*u3;
t8 = Q2_4.*u2.*u4;
t9 = Q2_5.*u2.*u5;
t10 = Q2_6.*u2.*u6;
t11 = Q3_4.*u3.*u4;
t12 = Q3_5.*u3.*u5;
t13 = Q3_6.*u3.*u6;
t14 = Q4_5.*u4.*u5;
t15 = Q4_6.*u4.*u6;
t16 = Q5_6.*u5.*u6;
out1 = reshape([Q1_1.*u1.^2,t2,t3,t4,t5,t6,t2,Q2_2.*u2.^2,t7,t8,t9,t10,t3,t7,Q3_3.*u3.^2,t11,t12,t13,t4,t8,t11,Q4_4.*u4.^2,t14,t15,t5,t9,t12,t14,Q5_5.*u5.^2,t16,t6,t10,t13,t15,t16,Q6_6.*u6.^2],[6,6]);
end
